test-ractor: support Ruby 3.5 (#231)
`Ractor#take` will be replaced at Ruby 3.5.
Ref. https://bugs.ruby-lang.org/issues/21262

This patch will fix error of `NoMethodError: undefined method 'take' for
an instance of Ractor`:

```
$ ruby -v
ruby 3.5.0dev (2025-10-23T04:08:26Z master 3b190855ba) +PRISM [arm64-darwin25]

$ rake test
/Users/watson/.rbenv/versions/3.5-dev/bin/ruby test/run-test.rb
/Users/watson/.rbenv/versions/3.5-dev/lib/ruby/gems/3.5.0+4/gems/groonga-command-1.5.3/lib/groonga/command/format/uri.rb:19: warning: CGI library is removed from Ruby 3.5. Please use cgi/escape instead for CGI.escape and CGI.unescape features.
If you need to use the full features of CGI library, Please install cgi gem.
Loaded suite test/run-test
Started
//Users/watson/prj/rroonga/test/test-ractor.rb:51: warning: Ractor is experimental, and the behavior may change in future versions of Ruby! Also there are many implementation issues.
E
============================================================================================================================================
Error: test: select(RactorTest): NoMethodError: undefined method 'take' for an instance of Ractor
/Users/watson/prj/rroonga/test/test-ractor.rb:63:in 'block in <class:RactorTest>'
============================================================================================================================================
O
============================================================================================================================================
Omission: This test is only for Linux system. [test_to_json_with_leap_second(RecordTest::JSONTest)]
/Users/watson/prj/rroonga/test/groonga-test-utils.rb:185:in 'GroongaTestUtils#only_linux'
============================================================================================================================================
O
============================================================================================================================================
Omission: Apache Arrow support is required [test_dump_column_names(TableArrowTest)]
/Users/watson/prj/rroonga/test/test-table-arrow.rb:22:in 'TableArrowTest#setup'
============================================================================================================================================
O
============================================================================================================================================
Omission: Apache Arrow support is required [test_dump_columns(TableArrowTest)]
/Users/watson/prj/rroonga/test/test-table-arrow.rb:22:in 'TableArrowTest#setup'
============================================================================================================================================
O
============================================================================================================================================
Omission: Apache Arrow support is required [test_float(TableArrowTest)]
/Users/watson/prj/rroonga/test/test-table-arrow.rb:22:in 'TableArrowTest#setup'
============================================================================================================================================
O
============================================================================================================================================
Omission: Apache Arrow support is required [test_int16(TableArrowTest)]
/Users/watson/prj/rroonga/test/test-table-arrow.rb:22:in 'TableArrowTest#setup'
============================================================================================================================================
O
============================================================================================================================================
Omission: Apache Arrow support is required [test_int32(TableArrowTest)]
/Users/watson/prj/rroonga/test/test-table-arrow.rb:22:in 'TableArrowTest#setup'
============================================================================================================================================
O
============================================================================================================================================
Omission: Apache Arrow support is required [test_int64(TableArrowTest)]
/Users/watson/prj/rroonga/test/test-table-arrow.rb:22:in 'TableArrowTest#setup'
============================================================================================================================================
O
============================================================================================================================================
Omission: Apache Arrow support is required [test_int8(TableArrowTest)]
/Users/watson/prj/rroonga/test/test-table-arrow.rb:22:in 'TableArrowTest#setup'
============================================================================================================================================
O
============================================================================================================================================
Omission: Apache Arrow support is required [test_time(TableArrowTest)]
/Users/watson/prj/rroonga/test/test-table-arrow.rb:22:in 'TableArrowTest#setup'
============================================================================================================================================
O
============================================================================================================================================
Omission: Apache Arrow support is required [test_uint16(TableArrowTest)]
/Users/watson/prj/rroonga/test/test-table-arrow.rb:22:in 'TableArrowTest#setup'
============================================================================================================================================
O
============================================================================================================================================
Omission: Apache Arrow support is required [test_uint32(TableArrowTest)]
/Users/watson/prj/rroonga/test/test-table-arrow.rb:22:in 'TableArrowTest#setup'
============================================================================================================================================
O
============================================================================================================================================
Omission: Apache Arrow support is required [test_uint64(TableArrowTest)]
/Users/watson/prj/rroonga/test/test-table-arrow.rb:22:in 'TableArrowTest#setup'
============================================================================================================================================
O
============================================================================================================================================
Omission: Apache Arrow support is required [test_uint8(TableArrowTest)]
/Users/watson/prj/rroonga/test/test-table-arrow.rb:22:in 'TableArrowTest#setup'
============================================================================================================================================
O
============================================================================================================================================
Omission: append for non table domain column isn't supported by Groonga. [test_append(VariableSizeColumnTest::VectorTest::StringTest)]
/Users/watson/prj/rroonga/test/test-variable-size-column.rb:247:in 'VariableSizeColumnTest::VectorTest::StringTest#test_append'
============================================================================================================================================
O
============================================================================================================================================
Omission: prepend for non table domain column isn't supported by Groonga. [test_prepend(VariableSizeColumnTest::VectorTest::StringTest)]
/Users/watson/prj/rroonga/test/test-variable-size-column.rb:256:in 'VariableSizeColumnTest::VectorTest::StringTest#test_prepend'
============================================================================================================================================
Finished in 15.166741 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------
1094 tests, 1539 assertions, 0 failures, 1 errors, 0 pendings, 15 omissions, 0 notifications
99.9073% passed
--------------------------------------------------------------------------------------------------------------------------------------------
72.13 tests/s, 101.47 assertions/s
rake aborted!
Command failed with status (1): [/Users/watson/.rbenv/versions/3.5-dev/bin/ruby test/run-test.rb]
/Users/watson/prj/rroonga/Rakefile:58:in 'block in <top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)
```